GestionDocumental/Models/persona.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public persona()
        {
            this.documento1 = new HashSet<documento>();
        }
    
        public int IdPersona { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string documento { get; set; }
        public string telefono { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public bool estado { get; set; }
        public int Id_Area { get; set; }
        public int Id_Rol { get; set; }
        public int Id_Sede { get; set; }
    
        public virtual area area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento> documento1 { get; set; }
        public virtual rol rol { get; set; }
        public virtual sede sede { get; set; }
    }
}

GestionDocumental/Controllers/PersonaController.cs
using GestionDocumental.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GestionDocumental.Filters;

namespace GestionDocumental.Controllers
{
    public class PersonaController : Controller
    {
        proyecto_radicadoEntities1 __ConnectBD;

        public PersonaController()
        {
            __ConnectBD = new proyecto_radicadoEntities1();
        }

        [PermisosRol(new int[] {1})]
        // GET: Persona
        public ActionResult Index()
        {
            try
            {
                List<ListViewPersona> lista;

                lista = (from x in __ConnectBD.persona
                         select new ListViewPersona
                         {
                             IdPersona = x.IdPersona,
                             primerNombre = x.primerNombre,
                             segundoNombre = x.segundoNombre,
                             primerApellido = x.primerApellido,
                             segundoApellido = x.segundoApellido,
                             documento = x.documento,
                             estado = x.estado
                         }
                         ).ToList();
                return View(lista);
            }
            catch (Exception ex)
            {
                return View(ex.Message);
                throw;
            }
        }

        public ActionResult Create()
        {
            try
            {
                List<ListViewArea> listArea;
                List<ListViewRol> listRol;
                List<ListViewSede> listSede;
                //Consulta Areas
                listArea = (from x in __ConnectBD.area
                            where x.estado == true
                            select new ListViewArea
                            {
                                Id_sede = x.IdArea,
                                Nombre_Area = x.nombreArea
                            }).ToList();
                //Consultar roles
                listRol = (from x in __ConnectBD.rol
                           select new ListViewRol
                           {
                               IdRol = x.IdRol,
                               nombreRol = x.nombreRol
                           }).ToList();

                //Consultar Sede
                listSede = (from x in __ConnectBD.sede
                            where x.estado == true
                            select new ListViewSede
                            {
                                SedeId = x.IdSede,
                                SedeName = x.nombreSede
                            }).ToList();

                List<SelectListItem> itemsArea = listArea.ConvertAll(t =>
                {
                    return new SelectListItem()
                    {
                        Text = t.Nombre_Area.ToString(),
                        Value = t.Id_sede.ToString(),
                        Selected = false
                    };
                });

                List<SelectListItem> itemsSede = listSede.ConvertAll(t =>
                {
                    return new SelectListItem()
                    {
                        Text = t.SedeName.ToString(),
                        Value = t.SedeId.ToString(),
                        Selected = false
                    };
                });

                List<SelectListItem> itemsRol = listRol.ConvertAll(t =>
                {
                    return new SelectListItem()
                    {
                        Text = t.nombreRol.ToString(),
                        Value = t.IdRol.ToString(),
                        Selected = false
                    };
                });

                ViewBag.itemsSede = itemsSede;
                ViewBag.itemsRol = itemsRol;
                ViewBag.itemsArea = itemsArea;
                return View();
            }
            catch (Exception ex)
            {
                //throw (ex);
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ListViewPersona collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var table = new persona();
                    table.primerNombre = collection.primerNombre;
                    table.segundoNombre = collection.segundoNombre;
                    table.primerApellido = collection.primerApellido;
                    table.segundoApellido = collection.segundoApellido;
                    table.documento = collection.documento;
                    table.telefono = collection.telefono;
                    table.usuario = collection.usuario;
                    table.clave = collection.clave;
                    table.estado = collection.estado;
                    table.Id_Area = collection.Id_Area;
                    table.Id_Rol = collection.Id_Rol;
                    table.Id_Sede = collection.Id_Sede;
                    __ConnectBD.persona.Add(table);
                    __ConnectBD.SaveChanges();
                    return RedirectToAction("Index");
                }

                List<ListViewArea> listArea;
                List<ListViewRol> listRol;
                List<ListViewSede> listSede;
                //Consulta Areas
                listArea = (from x in __ConnectBD.area
                            select new ListViewArea
                            {
                                Id_sede = x.IdArea,
                                Nombre_Area = x.nombreArea
                            }).ToList();
                //Consultar roles
                listRol = (from x in __ConnectBD.rol
                           select new ListViewRol
                           {
                               IdRol = x.IdRol,
                               nombreRol = x.nombreRol
                           }).ToList();


                //Consultar Sede
                listSede = (from x in __ConnectBD.sede
                            select new ListViewSede
                            {
                                SedeId = x.IdSede,
                                SedeName = x.nombreSede
                            }).ToList();

                List<SelectListItem> itemsArea = listArea.ConvertAll(t =>
                {
                    return new SelectListItem()
                    {
                        Text = t.Nombre_Area.ToString(),
                        Value = t.Id_sede.ToString(),
                        Selected = false
                    };
                });

                List<SelectListItem> itemsSede = listSede.ConvertAll(t =>
                {
                    return new SelectListItem()
                    {
                        Text = t.SedeName.ToString(),
                        Value = t.SedeId.ToString(),
                        Selected = false
                    };
                });

                List<SelectListItem> itemsRol = listRol.ConvertAll(t =>
                {
                    return new SelectListItem()
                    {
                        Text = t.nombreRol.ToString(),
                        Value = t.IdRol.ToString(),
                        Selected = false
                    };
                });

                ViewBag.itemsSede = itemsSede;
                ViewBag.itemsRol = itemsRol;
                ViewBag.itemsArea = itemsArea;
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            try
            {
                var table = __ConnectBD.persona.Find(Id);
                __ConnectBD.persona.Remove(table);
                __ConnectBD.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                //throw (ex);
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        } 


        public ActionResult Edit(int id)
        {
            try
            {
                List<ListViewSede> listSede = null;
                List<ListViewArea> listArea;
                List<ListViewRol> listRol;
                ListViewPersona model = new ListViewPersona();
                
                    var table = __ConnectBD.persona.Find(id); //encuentra el id del registro
                    model.IdPersona = table.IdPersona;
                    model.primerNombre = table.primerNombre;
                    model.segundoNombre = table.segundoNombre;
                    model.primerApellido = table.primerApellido;
                    model.segundoApellido = table.segundoApellido;
                    model.documento = table.documento;
                    model.telefono = table.telefono;
                    model.usuario = table.usuario;
                    model.clave = table.clave;
                    model.estado = table.estado;
                    model.Id_Area = table.Id_Area;
                    model.Id_Rol = table.Id_Rol;
                    model.Id_Sede = table.Id_Sede;

                //Consulta Areas
                listArea = (from x in __ConnectBD.area
                            select new ListViewArea
                            {
                                Id_sede = x.IdArea,
                                Nombre_Area = x.nombreArea
                            }).ToList();
                //Consultar roles
                listRol = (from x in __ConnectBD.rol
                           select new ListViewRol
                           {
                               IdRol = x.IdRol,

GestionDocumental/Views/Persona/Create.cshtml
@model GestionDocumental.Models.ListViewPersona
@{
    ViewBag.Title = "Create";
    IEnumerable<SelectListItem> itemsArea = (IEnumerable<SelectListItem>)ViewBag.itemsArea;
    IEnumerable<SelectListItem> itemsRol = (IEnumerable<SelectListItem>)ViewBag.itemsRol;
    IEnumerable<SelectListItem> itemsSede = (IEnumerable<SelectListItem>)ViewBag.itemsSede;
}

@using (Html.BeginForm("Create", "Persona", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <h2>Create</h2>

    <div class="form-horizontal">
        <h4>Nueva Persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.primerNombre, "Primer nombre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.primerNombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.primerNombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.segundoNombre, "Segundo nombre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.segundoNombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.segundoNombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.primerApellido, "Primer apellido", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.primerApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.primerApellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.segundoApellido, "Segundo apellido", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.segundoApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.segundoApellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.documento, "Documento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.documento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.documento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, "Teléfono", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.usuario, "Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.clave, "Clave", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.clave, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.clave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Area, "Area", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Area", itemsArea, "Seleccione...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Rol, "Rol", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Rol", itemsRol, "Seleccione...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Rol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Sede, "Sede", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Sede", itemsSede, "Seleccione...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Sede, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atrás", "Index")
</div>

GestionDocumental/Views/Persona/Edit.cshtml
@model GestionDocumental.Models.ListViewPersona
@{
    IEnumerable<SelectListItem> itemsArea = (IEnumerable<SelectListItem>)ViewBag.itemsArea;
    IEnumerable<SelectListItem> itemsRol = (IEnumerable<SelectListItem>)ViewBag.itemsRol;
    IEnumerable<SelectListItem> itemsSede = (IEnumerable<SelectListItem>)ViewBag.itemsSede;
}

@using (Html.BeginForm("Update", "Persona", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <h4>@ViewBag.message</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdPersona)
    <div class="form-group">
        @Html.LabelFor(model => model.primerNombre, "Primer nombre", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.primerNombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.primerNombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.segundoNombre, "Segundo nombre", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.segundoNombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.segundoNombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.primerApellido, "Primer apellido", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.primerApellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.primerApellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.segundoApellido, "Segundo apellido", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.segundoApellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.segundoApellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.documento, "Documento", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.documento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.documento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.telefono, "Teléfono", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.usuario, "Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.usuario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.usuario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.clave, "Clave", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.clave, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.clave, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_Area, "Area", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Id_Area", itemsArea, "Seleccione...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Id_Area, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_Rol, "Rol", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Id_Rol", itemsRol, "Seleccione...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Id_Rol, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_Sede, "Sede", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Id_Sede", itemsSede, "Seleccione...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Id_Sede, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Actualizar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Atrás", "Index")
</div>

GestionDocumental/Views/Persona/Index.cshtml
@model List<GestionDocumental.Models.ListViewPersona>

<p>
    @Html.ActionLink("Nueva Persona", "Create")
</p>

<table class="table">
    <tr>
        <th>
            ID
        </th>
        <th>
            Nombre
        </th>
        <th>
            Documento
        </th>
        <th>
            Estado
        </th>
        <th>
            Funciones
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPersona)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.primerNombre)
                @Html.DisplayFor(modelItem => item.segundoNombre)
                @Html.DisplayFor(modelItem => item.primerApellido)
                @Html.DisplayFor(modelItem => item.segundoApellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.documento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.estado)
            </td>
            <td>
                @Html.ActionLink("Eliminar", "Delete", new { id = item.IdPersona })
                @Html.ActionLink(" ", "Edit", new { id = item.IdPersona }, new { @class = "glyphicon glyphicon-edit", style = "color: black" })
                @*@Html.ActionLink(" ", "Status", new { id = item.IdPersona }, new { @class = "glyphicon glyphicon-lock" })*@
            </td>
        </tr>
    }



</table>

GestionDocumental/Views/Persona/prb.cshtml
<h1>@ViewBag.Message</h1>