GestionDocumental/Controllers/TipoController.cs
using GestionDocumental.Filters;
using GestionDocumental.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionDocumental.Controllers
{
   
    public class TipoController : Controller
    {
        proyecto_radicadoEntities1 __ConnectBD;
        // GET: Tipo

        public TipoController()
        {
            __ConnectBD = new proyecto_radicadoEntities1();
        }

        [PermisosRol(new int[] { 1 })]
        public ActionResult Index()
        {
            List<ListViewTipo> lista;
            
                lista = (from x in __ConnectBD.tipoDocumento
                         select new ListViewTipo
                         {
                             tipoDocumentoId = x.IdTipoDocumento,
                             nombreDocumento = x.nombreDocumento,
                             tiempoRes = x.tiempoRespuesta,
                             Estado = x.estado
                         }
                         ).ToList();
            return View(lista);
        }

        [PermisosRol(new int[] { 1 })]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [PermisosRol(new int[] { 1 })]
        public ActionResult Create(ListViewTipo collection)
        {
            try
            {
                    var table = new tipoDocumento();
                    table.nombreDocumento = collection.nombreDocumento;
                    table.tiempoRespuesta = collection.tiempoRes;
                    table.estado = true;
                    __ConnectBD.tipoDocumento.Add(table);
                    __ConnectBD.SaveChanges();
                    return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [PermisosRol(new int[] { 1 })]
        public ActionResult getId(int id)
        {
            try
            {
                ListViewTipo model = new ListViewTipo();
                
                    var table = __ConnectBD.tipoDocumento.Find(id);
                    model.tipoDocumentoId = table.IdTipoDocumento;
                    model.nombreDocumento = table.nombreDocumento;
                    model.tiempoRes = table.tiempoRespuesta;
                    model.Estado = table.estado;
                
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermisosRol(new int[] { 1 })]
        public ActionResult Edit(ListViewTipo collection)
        {
            try
            {

                    var table = __ConnectBD.tipoDocumento.Find(collection.tipoDocumentoId);
                    table.nombreDocumento = collection.nombreDocumento;
                    table.tiempoRespuesta = collection.tiempoRes;
                    table.estado = collection.Estado;
                    __ConnectBD.Entry(table).State = System.Data.Entity.EntityState.Modified;
                    __ConnectBD.SaveChanges();

                return Redirect("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        }
        
        [HttpGet]
        [PermisosRol(new int[] { 1 })]
        public ActionResult Delete(int Id)
        {
            try
            {
                    var table = __ConnectBD.tipoDocumento.Find(Id);
                    __ConnectBD.tipoDocumento.Remove(table);
                    __ConnectBD.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        }
    }
}

GestionDocumental/Views/Tipo/Create.cshtml
@model GestionDocumental.Models.ListViewTipo

<h2>Creacion de Tipo Documento</h2>

@using (Html.BeginForm("Create", "Tipo", FormMethod.Post))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <h4>Nueva Tipo Documento</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.nombreDocumento, "Tipo Documento", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombreDocumento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombreDocumento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tiempoRes, "Tiempo de Respuesta", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.tiempoRes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tiempoRes, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>

}

<div>
    @Html.ActionLink("Atrás", "Index")
</div>

GestionDocumental/Views/Tipo/Index.cshtml
@model List<GestionDocumental.Models.ListViewTipo>
<p>
    @Html.ActionLink("Nuevo Tipo de Documento", "Create")
</p>

<h2>Tipo Documento</h2>

<table class="table">
    <tr>
        <th>
            ID
        </th>
        <th>
            Documento
        </th>
        <th>
            Tiempo Respuesta
        </th>
        <th>
            Funciones
        </th>
        <th>
            Estado
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tipoDocumentoId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombreDocumento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tiempoRes) Dias
            </td>
            <td>
                @Html.ActionLink("Eliminar", "Delete", new { id = item.tipoDocumentoId })
                @Html.ActionLink(" ", "getId", new { id = item.tipoDocumentoId }, new { @class = "glyphicon glyphicon-edit", style = "color: black" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
        </tr>
    }

</table>

GestionDocumental/Views/Tipo/getId.cshtml
@model GestionDocumental.Models.ListViewTipo

@using (Html.BeginForm("Edit", "Tipo", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>Editar Tipo de Documento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.tipoDocumentoId)
        <div class="form-group">
            @Html.LabelFor(model => model.nombreDocumento, "Tipo Documento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombreDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombreDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tiempoRes, "Dias de Respuesta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tiempoRes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tiempoRes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atrás", "Index")
</div>