GestionDocumental/Models/documento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int IdDocumento { get; set; }
        public System.DateTime fechaRadicado { get; set; }
        public System.DateTime fechaDocumento { get; set; }
        public System.DateTime fechaVence { get; set; }
        public string ubicacion { get; set; }
        public int Id_Persona { get; set; }
        public int Id_TipoDocumento { get; set; }
        public int Id_Estado { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual persona persona { get; set; }
        public virtual tipoDocumento tipoDocumento { get; set; }
    }
}

GestionDocumental/Controllers/DocumentoController.cs
using GestionDocumental.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionDocumental.Controllers
{
    public class DocumentoController : Controller
    {
        proyecto_radicadoEntities1 __ConnectBD;
        // GET: Documento

        public DocumentoController()
        {
            __ConnectBD = new proyecto_radicadoEntities1();
        }
        public ActionResult Index()
        {
            List<ListViewDocumento> lista; //Crea un objeto de tipo ListViewDocumento

            lista = (from x in __ConnectBD.documento
                     select new ListViewDocumento
                     {
                         IdDocumento = x.IdDocumento,
                         fechaRadicado = x.fechaRadicado,
                         fechaDocumento = x.fechaDocumento,
                         fechaVence = x.fechaVence,
                         ubicacion = x.ubicacion,
                         Id_Persona = x.Id_Persona,
                         Id_TipoDocumento = x.Id_TipoDocumento,
                         Id_Estado = x.Id_Estado
                     }).ToList();
            return View(lista);   
        }
        public ActionResult Create()
        {
            try
            {
                List<ListViewPersona> listPersona;
                List<ListViewTipo> listTipo;
                List<ListViewEstado> listEstado;

                listPersona = (from x in __ConnectBD.persona
                               select new ListViewPersona
                               {
                                   IdPersona = x.IdPersona,
                                   primerNombre = x.primerNombre,
                                   segundoNombre = x.segundoNombre,
                                   primerApellido = x.primerApellido
                               }).ToList();

                listEstado = (from x in __ConnectBD.estado
                            select new ListViewEstado
                            {
                                IdEstado = x.IdEstado,
                                nombreEstado = x.nombreEstado
                            }).ToList();

                listTipo = (from x in __ConnectBD.tipoDocumento
                            where x.estado == true
                            select new ListViewTipo
                            {
                                tipoDocumentoId = x.IdTipoDocumento,
                                nombreDocumento = x.nombreDocumento
                            }).ToList();

                List<SelectListItem> itemsPersona = listPersona.ConvertAll(t =>
                {
                    return new SelectListItem()
                    {
                        Text = t.primerNombre.ToString(),
                        Value = t.IdPersona.ToString(),
                        Selected = false
                    };
                });

                List<SelectListItem> itemsTipo = listTipo.ConvertAll(t =>
                {
                    return new SelectListItem()
                    {
                        Text = t.nombreDocumento.ToString(),
                        Value = t.tipoDocumentoId.ToString(),
                        Selected = false
                    };
                });

                List<SelectListItem> itemsEstado = listEstado.ConvertAll(t =>
                {
                    return new SelectListItem()
                    {
                        Text = t.nombreEstado.ToString(),
                        Value = t.IdEstado.ToString(),
                        Selected = false
                    };
                });

                ViewBag.itemsPersona = itemsPersona;
                ViewBag.itemsEstado = itemsEstado;
                ViewBag.itemsTipo = itemsTipo;

                return View();
            }
            catch (Exception)
            {

                throw;
            }          
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ListViewDocumento Collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //var table = documento();
                    string result = Collection.archivo.FileName;
                    string RutaSitio = Server.MapPath("~/");
                    var table = new documento();
                    string PathArchivo = Path.Combine(RutaSitio + "/Files/"+result);
                    table.ubicacion = PathArchivo;
                    table.fechaRadicado = DateTime.Today;
                    table.fechaDocumento = Collection.fechaDocumento;
                    var table1 = __ConnectBD.tipoDocumento.Find(Collection.Id_TipoDocumento);
                    double TiempoRes = Convert.ToDouble(table1.tiempoRespuesta);
                    table.fechaVence = table.fechaRadicado.AddDays(TiempoRes);
                    table.Id_Persona = Collection.Id_Persona;
                    table.Id_TipoDocumento = Collection.Id_TipoDocumento;
                    table.Id_Estado = Collection.Id_Estado;
                    __ConnectBD.documento.Add(table);
                    __ConnectBD.SaveChanges();
                    Collection.archivo.SaveAs(PathArchivo);
                } else
                {
                    
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        }
    }
}

GestionDocumental/Views/Documento/Create.cshtml
@model GestionDocumental.Models.ListViewDocumento

@{ 
    IEnumerable<SelectListItem> itemsPersona = (IEnumerable<SelectListItem>)ViewBag.itemsPersona;
    IEnumerable<SelectListItem> itemsTipo = (IEnumerable<SelectListItem>)ViewBag.itemsTipo;
    IEnumerable<SelectListItem> itemsEstado = (IEnumerable<SelectListItem>)ViewBag.itemsEstado;
}

@using (Html.BeginForm("Create", "Documento", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Formulario de radicación</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.fechaDocumento, "Fecha Documento", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.fechaDocumento, new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(model => model.fechaDocumento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.archivo,"Archivo", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.archivo, new { @class = "form-control", type = "file", accept = ".pdf" })
            @Html.ValidationMessageFor(model => model.archivo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_Persona,"Funcionario", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Id_Persona", itemsPersona, "Seleccione...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Id_Persona, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_TipoDocumento,"Tipo Solicitud", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Id_TipoDocumento", itemsTipo, "Seleccione...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Id_TipoDocumento, "", new { @class = "text-danger" })
        </div>
    </div>

    <!--<div class="form-group">
        @Html.LabelFor(model => model.Id_Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Id_Estado", itemsEstado, "Seleccione...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Id_Estado, "", new { @class = "text-danger" })
        </div>
    </div>-->

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

GestionDocumental/Views/Documento/Index.cshtml
@model List<GestionDocumental.Models.ListViewDocumento>
<h2 class="text-center" style="color:black"> <strong>Documento</strong></h2>
<p>
    @Html.ActionLink(".", "Create",null, new { @class = "btn btn-primary  glyphicon glyphicon-plus" }) <!---->
</p>
<table class="table table-striped table-bordered">
    <tr>
        <th>
            Id Documento
        </th>
        <th>
            Fecha Radicado
        </th>
        <th>
            Fecha Documento
        </th>
        <th>
            Fecha Vence
        </th>
        <th>
            Persona
        </th>
        <th>
            Tipo Documento
        </th>
        <th>
            Estado
        </th>
        <th>
            Funciones
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdDocumento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechaRadicado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechaDocumento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechaVence)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id_Persona)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id_TipoDocumento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id_Estado)
            </td>
            <td>
                @*<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Open modal for</button>
                @Html.ActionLink(".", "Edit", new { id = item.IdDocumento }, new { @class = "btn btn-warning glyphicon glyphicon-edit" })
                @Html.ActionLink(".", "", "", new { @class = "btn btn-info glyphicon glyphicon-eye-open", data_toggle = "modal", data_target = "#Details" })
                @Html.ActionLink(".", "Delete", new { id = item.IdDocumento }, new { @class = "btn btn-danger glyphicon glyphicon-trash" })*@
            </td>
        </tr>
    }

</table>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Recipient:</label>
                        <input type="text" class="form-control" id="recipient-name">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Message:</label>
                        <textarea class="form-control" id="message-text"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Send message</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="Details" tabindex="-1" role="dialog" aria-labelledby="DetailsLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Recipient:</label>
                        <input type="text" class="form-control" id="recipient-name">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Message:</label>
                        <textarea class="form-control" id="message-text"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Send message</button>
            </div>
        </div>
    </div>
</div>