GestionDocumental/Models/area.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public area()
        {
            this.persona = new HashSet<persona>();
        }
    
        public int IdArea { get; set; }
        public string nombreArea { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<persona> persona { get; set; }
    }
}

GestionDocumental/Controllers/AreaController.cs
using GestionDocumental.Filters;
using GestionDocumental.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace GestionDocumental.Controllers
{
   
    public class AreaController : Controller
    {
        [PermisosRol(new int[] { 1 })]
        // GET: Area
        public ActionResult Index()
        {
            List<ListViewArea> lista; //Crea un objeto de tipo ListViewArea
            using (proyecto_radicadoEntities1 db = new proyecto_radicadoEntities1())
            {
                lista = (from x in db.area
                         select new ListViewArea
                         {
                             Id_sede = x.IdArea,
                             Nombre_Area = x.nombreArea
                         }
                         ).ToList();

            }
            return View(lista);
        }

        [PermisosRol(new int[] { 1 })]
        // GET: Area/Create
        public ActionResult Create()
        {
            return View();
        }

        [PermisosRol(new int[] { 1 })]
        // POST: Area/Create
        [HttpPost]
        public ActionResult Create(ListViewArea collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (proyecto_radicadoEntities1 db = new proyecto_radicadoEntities1())
                    {
                        var table = new area();
                        table.nombreArea = collection.Nombre_Area;
                        table.estado = true;
                        //table.estado = true;
                        db.area.Add(table);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                //throw (ex);
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        }

        [PermisosRol(new int[] { 1 })]
        // GET: Area/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                ListViewArea model = new ListViewArea();
                using (proyecto_radicadoEntities1 bd = new proyecto_radicadoEntities1())
                {
                    var table = bd.area.Find(id); //encuentra el id del registro
                    model.Id_sede = table.IdArea;
                    model.Nombre_Area = table.nombreArea;
                    model.estado = table.estado;
                }
                return View(model); //Retorna los datos del registro seleccionado
            }
            catch (Exception ex)
            {
                //throw (ex);
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        }

        // POST: Area/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermisosRol(new int[] { 1 })]
        public ActionResult Editar(ListViewArea collection)
        {
            try
            {
                using (proyecto_radicadoEntities1 db = new proyecto_radicadoEntities1())
                {
                    var table = db.area.Find(collection.Id_sede);//Encuentra el registro a editar
                    table.nombreArea = collection.Nombre_Area;//Asigna valores al registro a editar
                    table.estado = collection.estado;//Asigna valores al registro a editar
                    db.Entry(table).State = System.Data.Entity.EntityState.Modified;//guarda cambios
                    db.SaveChanges();//confirma cambios
                }

                return Redirect("Index");
            }
            catch (Exception ex) 
            {
                //throw (ex);
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        }

        // GET: Area/Delete/5

        // POST: Area/Delete/5
        [HttpGet]
        [PermisosRol(new int[] { 1 })]
        public ActionResult Delete(int Id)
        {
            try
            {
                using (proyecto_radicadoEntities1 db = new proyecto_radicadoEntities1())
                {
                    var table = db.area.Find(Id);
                    db.area.Remove(table);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)    
            {
                //throw (ex);
                ModelState.AddModelError("", "Error" + ex);
                return View();
                throw;
            }
        }
    }
}

GestionDocumental/Views/Area/Create.cshtml
@model GestionDocumental.Models.ListViewArea

@using (Html.BeginForm("Create", "Area", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Nueva Area</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre_Area, "Nombre del Area", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Atrás", "Index")
</div>

GestionDocumental/Views/Area/Edit.cshtml
@model GestionDocumental.Models.ListViewArea

@using (Html.BeginForm("Editar", "Area", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <h4>Editar Area</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id_sede)
    <div class="form-group">
        @Html.LabelFor(model => model.Nombre_Area,"Nombre Area", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre_Area, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre_Area, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.estado,"Estado", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Actualizar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Atrás", "Index")
</div>

GestionDocumental/Views/Area/Index.cshtml
@model IEnumerable<GestionDocumental.Models.ListViewArea>

<p>
    @Html.ActionLink("Nueva Area", "Create")
</p>

<table class="table">
    <tr>
        <th>
            #
        </th>
        <th>
            Area
        </th>
        <th>
            Funciones
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(a => item.Id_sede)
            </td>
            <td>
                @Html.DisplayFor(a => item.Nombre_Area)
            </td>
            <td>
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Id_sede })
                @Html.ActionLink(".", "Edit", new { id = item.Id_sede }, new { @class = "glyphicon glyphicon-edit", style = "color: black" })
            </td>
        </tr>
    }
</table>